<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="MatchesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Match" Member="Matches">
    <Type Name="Match">
      <Column Name="MatchID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TalentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RedCards" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Yellowcards" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Timeplayed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Start" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="goals" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="GoalAssits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TacklesMade" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GoalsSaved" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fouls" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAvailable" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Passes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SuccessfulPasses" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShotONTarget" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>