<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="VideosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Video" Member="Videos">
    <Type Name="Video">
      <Column Name="VideoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VideoName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VideoDescption" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VideoFIleName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="VideoLikes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VideoViews" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isAvailable" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SportID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DatePosted" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>